#!/bin/bash

#corpora=("Heart of Darkness" "Kama Sutra" "Ulysses" "Moby Dick" "Moby Dick and the Kama Sutra")
corpora=("Dorian Gray" "Dracula" "Heart of Darkness" "Kama Sutra" "Satyricon" "The Metamorphosis" "The Turn of the Screw" "Ulysses" "Wizard of Oz" "Moby Dick" "Irish Fairy Tales")
#corpora=("Moby Dick and Ulysses" "Dorian Gray and The Satyricon" "Dracula and the Kama Sutra" "Heart of Darkness and The Wizard of Oz" "The Metamorphosis and The Turn of the Screw" "Irish Fairy Tales and Moby Dick")
#corpora=("Dorian Gray" "Dracula" "Heart of Darkness" "Kama Sutra" "Satyricon" "The Metamorphosis" "The Turn of the Screw" "Ulysses" "Wizard of Oz" "Moby Dick" "Irish Fairy Tales" "Moby Dick and Ulysses" "Dorian Gray and The Satyricon" "Dracula and the Kama Sutra" "Heart of Darkness and The Wizard of Oz" "The Metamorphosis and The Turn of the Screw" "Irish Fairy Tales and Moby Dick")

while [ 1 ]
  do
    clear
    echo "Guillaume begins to write..."
    echo ""
    RANDOM=$$$(date +%s)
    corpus=${corpora[$RANDOM % ${#corpora[@]} ]}
    ruby -I lib ./bin/guillaume write -c "$corpus" -m 4
    sleep 60
    echo ""
  done

